### ISSUE TITLE
How to configure broker address in mode WIFI_AP_STA

### ISSUE THREAD

**Issue by hjindr** [martin-ger/uMQTTBroker#6]
Hello,
I want to thank you for creation and sharing this very good library.  I am new in this problematic - so sorry - maybe my question or idea is basically wrong. 
I have a question regarding Mqtt broker IP address. 
My conception is to have some ESP8266 clients as temperature sensors, and one ESP8266 which is running as broker and which controlls the heating thermostat relay.
Temperature sensors reports only temperatures. The broker receives the temperatures and decides, if it is necessary to start the heating. The heating start levels could be configured from outside app. 
I want to run the ESP broker in mode  WIFI_AP_STA, it means the ESP will be the access point for temperature sensors, and it will be independent on other wifi connection.
As a feature it could be connected to home wifi ( to have access over android app)
But now is the broker IP address the same as it receives from home wifi router (DHCP). 
Is it possible to set the broker address as AP IP?
I tried mDNS, to check if there is possible to connect the broker via hostname, (independent on IP)
but also without success.  Do you have any idea?
Thank you very much.
Best regards Jan Jindra

**Comment by martin-ger** [comment]
The ESP in  WIFI_AP_STA mode has two IP addresses, one for the STA interface and one for the SOFT_AP. 

The SOFT_AP interface is typically 192.168.4.1, the DHCP-server on the ESP distributes addresses in this subnet to its clients (in you case the temperature sensors). 

The STA interface receives its address via DHCP from the uplink AP (Home Router). This should be different from 192.168.4.x (otherwise you have to change one of the networks).

The MQTT broker is accessible via both interfaces and IP addresses, i.e. your temperature sensors can connect their MQTT client to 192.168.4.1 port 1883. An external Android App has to connect to the address assigned by the home router. mDNS is not supported by Android as far as I know. But typicall the home routers remember their DHCP leases and use the same address every time. Another option would be to assign a static IP address to broker in the uplink network (outside the range of it DHCP server). Then you have well known fixed address there as well.

**Comment by hjindr** [comment]
Hello Martin, thanks for the fast reply.
For me is possible to connect to the broker only with STA IP address - othervise the temp sensor connects to AP(192.168.4.1) succesfully and get IP 192.168.4.2 but the MQTT broker connection failed -, rc=-2  (I use PubSubClient.h)
Seems like the broker is running only with STA IP address - otherwise I am doing something wrong.

**Comment by martin-ger** [comment]
Hi,

the STA and the SOFT_AP interface have to bei in different IP subnets, 
otherweise routing fails.


Am 30. Januar 2018 3:47:26 nachm. schrieb hjindr <notifications@github.com>:

**Comment by martin-ger** [comment]
You might try my esp_mqtt project. This is a complete MQTT broker that uses 
the same lib and definitely works in both addresses.


Am 30. Januar 2018 3:47:26 nachm. schrieb hjindr <notifications@github.com>:

**Comment by hjindr** [comment]
Hello,
I must manually configure the SOFT AP  IP, Gateway and subnet and it starts working
Use WiFi.softAPConfig(local_ip, gateway, subnet); before starting soft AP.
Regards Jan
